#!/bin/bash
totalsum=0;
for i in libs/{cyform,cytpl,db/{classes,config,tests},jork,logger} tools/{cydocs,debug} system/classes/cyclone/{request,cli,config,autoloader}
do
modsum=0;
for file in `find $i -name '*'`; do
	if [ -f $file ]; then
		linecount=`wc -l $file | sed 's/ [a-zA-Z0-9\./_-]*//'`;
		let modsum=$modsum+$linecount;
	fi
done
echo "$i: $modsum";
let totalsum=$totalsum+$modsum
done

for file in index.php build.xml build.properties; do
linecount=`wc -l $file | sed 's/ [a-zA-Z0-9\./_]*//'`;
let totalsum=$totalsum+$linecount
done
echo "total: $totalsum"

