<?php
namespace app\controller;

use cyclone\request\SkeletonController;

/**
 * Default controller specified by the "default" route.
 */
class MainController extends SkeletonController {

    /**
     * The default action specified by the route.
     */
    public function action_index() {
        // $this->_response is an object representing the HTTP response generated by the application
        // we set the response body here
        $this->_response->body('Hello World!');
    }

}